In [13]:

import numpy as np
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,6,(3,3))
print("Array1 : \n",arr1)
print("Array2 : \n",arr2)
print("Multiply : \n",np.multiply(arr1,arr2))
print("Product : \n",np.prod([arr1,arr2]))
print("Dot : \n",np.dot(arr1,arr2))

Array1 : 
 [[4 3 3]
 [1 2 1]
 [4 1 1]]
Array2 : 
 [[5 2 1]
 [1 3 1]
 [2 4 3]]
Multiply : 
 [[20  6  3]
 [ 1  6  1]
 [ 8  4  3]]
Product : 
 207360
Dot : 
 [[29 29 16]
 [ 9 12  6]
 [23 15  8]]


In [17]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
print("Union : ",np.union1d(arr1,arr2))

print("Intersection : ",np.intersect1d(arr1,arr2))

print("Set Difference : ",np.setdiff1d(arr1,arr2))

print("XOR : ",np.setxor1d(arr1,arr2))

Union :  [1 2 3 4 5 6]
Intersection :  [3 4]
Set Difference :  [1 2]
XOR :  [1 2 5 6]


In [29]:
import numpy as np
arr1=np.random.randint(10 ,size=10)
print(arr1)
print("Cumulative sum : ",np.cumsum(arr1))
print("Cumulative Product : ",np.cumprod(arr1))
print("Discrete difference (with n=3) : ",np.diff(arr1, n=3))
print("The unique elements from the array : ",np.unique(arr1))

[0 0 4 1 6 1 1 0 1 3]
Cumulative sum :  [ 0  0  4  5 11 12 13 13 14 17]
Cumulative Product :  [0 0 0 0 0 0 0 0 0 0]
Discrete difference (with n=3) :  [-11  15 -18  15  -6   3  -1]
The unique elements from the array :  [0 1 3 4 6]


In [39]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
z=[]
for i,j in zip(arr1,arr2):
    z.append(i+j)
print(z)

print(np.add(arr1,arr2))

def adds(x,y):
    return x+y
result=np.frompyfunc(adds,2,1)
print(result(arr1,arr2))

[4, 6, 8, 10]
[ 4  6  8 10]
[4 6 8 10]


In [49]:
import numpy as np
arr1=np.array([[[1,2,3,4]]])
arr2=np.array([5,25,15,10])
print("LCM : ",np.lcm.reduce(arr1))
print("GCD : ",np.gcd.reduce(arr2))


LCM :  [[1 2 3 4]]
GCD :  5
