In [13]:

import numpy as np
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,6,(3,3))
print("Array1 : \n",arr1)
print("Array2 : \n",arr2)
print("Multiply : \n",np.multiply(arr1,arr2))
print("Product : \n",np.prod([arr1,arr2]))
print("Dot : \n",np.dot(arr1,arr2))

Array1 : 
 [[1 4 4]
 [4 4 3]
 [4 3 4]]
Array2 : 
 [[5 3 3]
 [2 5 2]
 [5 1 5]]
Multiply : 
 [[ 5 12 12]
 [ 8 20  6]
 [20  3 20]]
Product : 
 829440000
Dot : 
 [[33 27 31]
 [43 35 35]
 [46 31 38]]


In [14]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
print("Union : ",np.union1d(arr1,arr2))

print("Intersection : ",np.intersect1d(arr1,arr2))

print("Set Difference : ",np.setdiff1d(arr1,arr2))

print("XOR : ",np.setxor1d(arr1,arr2))

Union :  [1 2 3 4 5 6]
Intersection :  [3 4]
Set Difference :  [1 2]
XOR :  [1 2 5 6]


In [15]:
import numpy as np
arr1=np.random.randint(10 ,size=10)
print(arr1)
print("Cumulative sum : ",np.cumsum(arr1))
print("Cumulative Product : ",np.cumprod(arr1))
print("Discrete difference (with n=3) : ",np.diff(arr1, n=3))
print("The unique elements from the array : ",np.unique(arr1))

[0 7 9 5 3 7 0 6 9 8]
Cumulative sum :  [ 0  7 16 21 24 31 31 37 46 54]
Cumulative Product :  [0 0 0 0 0 0 0 0 0 0]
Discrete difference (with n=3) :  [ -1   8   4 -17  24 -16  -1]
The unique elements from the array :  [0 3 5 6 7 8 9]


In [16]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
z=[]
for i,j in zip(arr1,arr2):
    z.append(i+j)
print(z)

print(np.add(arr1,arr2))

def adds(x,y):
    return x+y
result=np.frompyfunc(adds,2,1)
print(result(arr1,arr2))

[4, 6, 8, 10]
[ 4  6  8 10]
[4 6 8 10]


In [17]:
import numpy as np
arr1=np.array([[[1,2,3,4]]])
arr2=np.array([5,25,15,10])
print("LCM : ",np.lcm.reduce(arr1))
print("GCD : ",np.gcd.reduce(arr2))


LCM :  [[1 2 3 4]]
GCD :  5
